var config = {
  // The following lines don't necessarily have to be 7 lines, you can also change it to 4 lines, 2 lines, etc.
  lines: [
    'My Dearest CryBaby and Bestie,',
    "In the chaos of life's tangled threads,",
    'Where broken dreams and fears embed,',
    'There blooms a hope, a guiding light,',
    "Love's gentle touch, so pure and bright.",
    '',
    'With tender hands and hearts entwined,',
    'We mend the wounds, the scars, the grind.',
    "For in each other's arms we find,",
    'The strength to heal, to redefine.',
    '',
    'Through trials faced and battles won,',
    'Our love endures, like the morning sun.',
    'In your embrace, I find my home,',
    'Where troubles fade, and fears are gone.',
    '',
    'Together, we paint the canvas anew,',
    'With hues of love, so deep and true.',
    'For in your eyes, I see the key,',
    "To fix everything, with love's decree.",
    '',
    'So let us journey, hand in hand,',
    'Across the oceans, over the land.',
    "For love's embrace, a soothing balm,",
    'That heals all wounds and brings us calm.',
    '',
    'In your love, I find my solace,',
    'A sanctuary, a sacred promise.',
    'With you, my dear, I am complete,',
    'Fixing everything, with love so sweet.',
    '',
    'Forgive me, for I am nothing without you...',
    'With every beat of my heart, I love you more than words can express,',
    'Forever yours, your Girly Gangsta...',
  ],
  // Date when the apology is being made. Format must be Year-Month-DayTTime:Minute:Second
  date: 'YYYY-MM-DDT00:00:00',
  // Names of both persons
  names: ['[Your Name]', 'My CryBaby and my Bestie'],
};
